"use strict";
const express=require("express");
const database=require("../config/database");
const {auth}=require("../middleware/auth");
const {requirePermission,getCargo}=require("../middleware/permissions");
let webpush=null;try{webpush=require("web-push")}catch(_){webpush=null}
const router=express.Router();let ready=false;
const clean=(v,n=1000)=>String(v||"").trim().slice(0,n);
const uid=req=>clean(req.usuario?.id||req.usuario?._id||req.usuarioDoc?._id,24);
async function ensure(){if(ready)return;await database.query(`CREATE TABLE IF NOT EXISTS push_subscriptions (endpoint_hash CHAR(64) NOT NULL PRIMARY KEY,endpoint TEXT NOT NULL,p256dh VARCHAR(255) NOT NULL,auth_key VARCHAR(255) NOT NULL,usuario_id CHAR(24) NOT NULL,email VARCHAR(190) NOT NULL DEFAULT '',plano VARCHAR(32) NOT NULL DEFAULT '',cargo VARCHAR(32) NOT NULL DEFAULT '',user_agent VARCHAR(500) NOT NULL DEFAULT '',ativa TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_push_user(usuario_id,ativa),KEY idx_push_email(email,ativa),KEY idx_push_destino(plano,cargo,ativa)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);ready=true}
function configured(){return Boolean(webpush&&process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY)}
function setup(){if(!configured())return false;webpush.setVapidDetails(process.env.VAPID_SUBJECT||"mailto:suporte@turmablack.com.br",process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);return true}
router.get("/push/public-key",(_req,res)=>res.json({sucesso:true,configured:configured(),publicKey:process.env.VAPID_PUBLIC_KEY||""}));
router.post("/push/subscribe",auth,async(req,res)=>{try{await ensure();const sub=req.body?.subscription||req.body;const endpoint=clean(sub?.endpoint,4000),p256dh=clean(sub?.keys?.p256dh,255),authKey=clean(sub?.keys?.auth,255);if(!endpoint||!p256dh||!authKey)return res.status(400).json({erro:"Assinatura push inválida."});const crypto=require("crypto"),hash=crypto.createHash("sha256").update(endpoint).digest("hex");await database.query(`INSERT INTO push_subscriptions(endpoint_hash,endpoint,p256dh,auth_key,usuario_id,email,plano,cargo,user_agent,ativa) VALUES(?,?,?,?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE endpoint=VALUES(endpoint),p256dh=VALUES(p256dh),auth_key=VALUES(auth_key),usuario_id=VALUES(usuario_id),email=VALUES(email),plano=VALUES(plano),cargo=VALUES(cargo),user_agent=VALUES(user_agent),ativa=1`,[hash,endpoint,p256dh,authKey,uid(req),clean(req.usuario?.email,190).toLowerCase(),clean(req.usuario?.plano,32).toLowerCase(),getCargo(req.usuario),clean(req.headers["user-agent"],500)]);return res.json({sucesso:true,mensagem:"Notificações ativadas neste dispositivo."})}catch(error){console.error("Erro push subscribe:",error);return res.status(500).json({erro:"Não foi possível ativar notificações push."})}});
router.post("/push/unsubscribe",auth,async(req,res)=>{try{await ensure();const endpoint=clean(req.body?.endpoint,4000);if(endpoint){const crypto=require("crypto"),hash=crypto.createHash("sha256").update(endpoint).digest("hex");await database.query("UPDATE push_subscriptions SET ativa=0 WHERE endpoint_hash=? AND usuario_id=?",[hash,uid(req)])}return res.json({sucesso:true})}catch{return res.status(500).json({erro:"Falha ao desativar push."})}});
function allowed(row,n){if(n.destino==="todos")return true;if(n.destino==="premium")return row.plano!=="free";if(n.destino==="free")return row.plano==="free";if(n.destino==="especifico")return (n.usuario_id&&n.usuario_id===row.usuario_id)||(n.email&&n.email.toLowerCase()===row.email.toLowerCase());if(n.destino==="admin")return ["dev","dono","superadmin","admin","financeiro","moderador","suporte"].includes(row.cargo);if(n.destino==="superadmin")return ["dev","dono","superadmin"].includes(row.cargo);if(n.destino==="moderadores")return row.cargo==="moderador";if(n.destino==="suporte")return row.cargo==="suporte";if(n.destino==="vendedores")return ["vendedor","financeiro","admin","dono","dev"].includes(row.cargo);return false}
router.post("/push/enviar/:id",auth,requirePermission("notificacoes"),async(req,res)=>{try{await ensure();if(!setup())return res.status(503).json({erro:"Configure VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY e VAPID_SUBJECT na Hostinger."});const notes=await database.query("SELECT * FROM notificacoes WHERE id=? AND ativa=1 LIMIT 1",[clean(req.params.id,24)]);const n=notes[0];if(!n)return res.status(404).json({erro:"Notificação não encontrada."});const rows=await database.query("SELECT * FROM push_subscriptions WHERE ativa=1");const targets=rows.filter(row=>allowed(row,n));let sent=0,failed=0;await Promise.allSettled(targets.map(async row=>{try{await webpush.sendNotification({endpoint:row.endpoint,keys:{p256dh:row.p256dh,auth:row.auth_key}},JSON.stringify({id:n.id,title:n.titulo,body:n.mensagem,link:n.link||"/dashboard",prioridade:n.prioridade,icon:"/assets/turma-primo-logo.svg"}));sent++}catch(error){failed++;if(error.statusCode===404||error.statusCode===410)await database.query("UPDATE push_subscriptions SET ativa=0 WHERE endpoint_hash=?",[row.endpoint_hash])}}));return res.json({sucesso:true,enviadas:sent,falhas:failed,assinaturas:targets.length})}catch(error){console.error("Erro ao enviar push:",error);return res.status(500).json({erro:"Falha ao enviar notificações push."})}});
router.get("/push/status",async(_req,res)=>{try{await ensure();const rows=await database.query("SELECT COUNT(*) total,SUM(ativa=1) ativas FROM push_subscriptions");return res.json({sucesso:true,configured:configured(),total:Number(rows[0]?.total||0),ativas:Number(rows[0]?.ativas||0)})}catch{return res.status(500).json({erro:"Falha ao consultar push."})}});
module.exports=router;