"use strict";
const crypto=require('node:crypto'),db=require('../config/database'),{withTransaction}=require('./db-transaction'),{error}=require('./student-records'),C=require('../public/study-curriculum');
let ready;
function calendar(now=new Date()){
 const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now),v=Object.fromEntries(parts.map(p=>[p.type,p.value])),date=`${v.year}-${v.month}-${v.day}`,weekday=new Date(date+'T12:00:00Z').getUTCDay();
 return {date,weekday,kind:weekday===0?'primo':weekday===6?'weekly':'daily',count:weekday===0?25:weekday===6?20:10,level:weekday===0?6:weekday===6?5:weekday,timezone:'America/Sao_Paulo'};
}
const labels={daily:'Prova diária',weekly:'Prova semanal',primo:'Desafio do Primo'},levels=['','Fundamentos','Aplicação','Intermediária','Avançada','Alta','Extrema'];
const canonical=a=>[...new Set(a)].sort((x,y)=>x-y).join(', ');
function shuffled(list){const out=[...list];for(let i=out.length-1;i>0;i--){const j=crypto.randomInt(i+1);[out[i],out[j]]=[out[j],out[i]];}return out;}
function question(module,prompt,right,alternatives,explanation,level){
 const correct=String(right),options=shuffled([...new Set([correct,...alternatives.map(String)])].slice(0,4));
 if(options.length!==4)return null;
 return {module,prompt,options,correct:options.indexOf(correct),explanation,level,key:crypto.createHash('sha256').update(module+'|'+prompt).digest('hex')};
}
function bank(){
 const out=[];const add=(...a)=>{const q=question(...a);if(q)out.push(q)};
 for(let n=0;n<=36;n++){
  const ns=C.neighbors(n,1),targets=C.magnets[n];
  add('magneto',`Consulte o mapa Magneto. Quais são todos os destinos da origem ${n}?`,canonical(targets),[canonical(C.magnets[(n+1)%37]),canonical(C.magnets[(n+9)%37]),String(n),canonical(ns)],`Na tabela do módulo, ${n} aponta para ${canonical(targets)}. A relação é direcional.`,1);
  const coverage=[...new Set([n,...targets].flatMap(x=>C.neighbors(x,1)))].length;
  add('magneto',`Na origem ${n}, una as regiões de todos os destinos e da origem, com um vizinho por lado. Quantos números distintos há?`,coverage,[coverage+1,Math.max(0,coverage-1),coverage+3],`Conjunto sem repetições: ${canonical([n,...targets].flatMap(x=>C.neighbors(x,1)))}.`,4);
  add('magneto',`Na Race, quais são os dois vizinhos imediatos de ${n}, sem incluir a origem?`,canonical(ns.filter(x=>x!==n)),[canonical([Math.max(0,n-1),(n+1)%37]),canonical(C.neighbors((n+3)%37,1).filter(x=>x!==(n+3)%37)),canonical([0,36]),canonical([7,24])],`Na ordem europeia, o trecho é ${ns.join(' → ')}.`,2);
  const f=C.familyOf(n);
  add('cavalo',`O resultado ${n} pertence a qual família do Cavalo?`,f<0?'Fora das famílias':`Cavalo ${f+1}`,['Cavalo 1','Cavalo 2','Cavalo 3','Fora das famílias'],`${n} termina em ${n%10}. Os grupos são 1/4/7, 2/5/8, 3/6/9; terminal zero fica fora.`,1);
  if(n>=10){const d=C.digitResults(n);add('camaleoes',`Calcule a soma e a diferença absoluta dos dígitos de ${n}. Qual é o conjunto de resultados?`,canonical(d),[String(n%10),String(n),canonical([d[0]+1,d.at(-1)+1]),'0'],`${Math.floor(n/10)} + ${n%10} = ${d[0]}; diferença absoluta = ${Math.abs(Math.floor(n/10)-n%10)}.`,2);}
  if(C.mirrors[n]!==undefined){const mirror=C.mirrors[n];add('espelhos',`Qual é o espelho de ${n} cadastrado no módulo?`,mirror,[n,(mirror+1)%37,(mirror+2)%37,(mirror+3)%37],`A tabela relaciona ${n} e ${mirror}.`,1);
   const r=C.reading('espelhos',[n],2);add('espelhos',`Para a origem ${n}, una espelho com 3 vizinhos, origem com 1 e extras específicos. Quantos números distintos ficam marcados?`,r.coverage.length,[r.coverage.length+1,r.coverage.length-1,r.coverage.length+3],`Cobertura: ${canonical(r.coverage)}. Extras: ${n===1?'11 e 0':n===2?'22':n===3?'33':'nenhum'}.`,4);
  }
  for(let b=0;b<=36;b+=3){const results=C.pairResults(n,b);add('fibonacci',`No par ${n} e ${b}, quais resultados válidos entre 0 e 36 vêm da soma e da diferença?`,canonical(results),[canonical([n+b]),canonical([Math.abs(n-b)+1]),canonical([n,b]),'Nenhum'],`Soma ${n+b}${n+b>36?' descartada por superar 36':''}; diferença ${Math.abs(n-b)}.`,3);}
  if(f>=0){const other=(n+7)%37,fo=C.familyOf(other);add('cavalo',`Compare ${n} e ${other}. Qual leitura dos terminais está correta?`,`${n}: Cavalo ${f+1}; ${other}: ${fo<0?'fora':`Cavalo ${fo+1}`}`,[`${n}: Cavalo ${(f+1)%3+1}; ${other}: fora`,`${n}: fora; ${other}: Cavalo 1`,'Some os dígitos antes de classificar'],`Use somente o último dígito: ${n%10} e ${other%10}.`,3);}
 }
 for(const n of [11,22,33]){const r=C.reading('gemeos',[n],2);add('gemeos',`Se o gêmeo de origem é ${n}, quais são os outros dois membros?`,canonical(r.targets),[canonical([n,...r.targets.slice(0,1)]),'10, 20','11, 22, 33'],`Retire ${n} da família 11, 22, 33.`,1);
 for(let k=1;k<=3;k++){const set=[...new Set([...r.targets.flatMap(x=>C.neighbors(x,k)),...C.neighbors(n,1)])];add('gemeos',`Exercício de comparação: origem ${n} com 1 vizinho e os dois alvos com ${k} por lado. Qual o total sem repetição?`,set.length,[set.length+1,set.length-1,set.length+3],`${canonical(set)}. A regra base da aula usa 2 vizinhos nos alvos; aqui o valor ${k} é uma variação explícita.`,4);}}
 C.triangles.forEach(t=>t.points.forEach((p,i)=>{const known=t.points.filter((_,j)=>j!==i);add('pitagoras',`Na família ${t.name}, os conhecidos são ${known.join(' e ')}. Qual integrante falta?`,p,[(p+1)%37,(p+2)%37,(p+3)%37],`Família completa: ${t.points.join(', ')}.`,2);
 const count=[...new Set(t.points.flatMap(x=>C.neighbors(x,1)))].length;add('pitagoras',`Família ${t.name}: unindo os 3 vértices e 1 vizinho por lado, quantos números distintos resultam?`,count,[count+1,count-1,count+3],`União das regiões: ${canonical(t.points.flatMap(x=>C.neighbors(x,1)))}.`,5);}));
 for(let n=10;n<=36;n++){const d=C.digitResults(n);for(let m=n+1;m<=36;m++){const common=d.filter(x=>C.digitResults(m).includes(x));if(common.length)add('camaleoes',`Quais resultados de soma/diferença dos dígitos são comuns a ${n} e ${m}?`,canonical(common),[canonical(d.map(x=>x+1)),String(n%10),String(m),String(n)],`${n} gera ${canonical(d)}; ${m} gera ${canonical(C.digitResults(m))}. A interseção é ${canonical(common)}.`,5);}}
 for(let n=0;n<=36;n++){add('eclipse',`No Eclipse Zero, onde se classifica o número ${n}?`,n%10===0?'Principal':n%10===9?'Complemento':'Fora dos dois grupos',['Principal','Complemento','Fora dos dois grupos','Nos dois grupos'],`Terminal 0: 0, 10, 20, 30. Terminal 9: 9, 19, 29. ${n} termina em ${n%10}.`,1);
 const region=C.neighbors(n,2),intersection=region.filter(x=>x%10===0||x%10===9);add('eclipse',`No trecho de Race com centro ${n} e dois vizinhos por lado, quantos pertencem aos terminais 0 ou 9?`,intersection.length,[intersection.length+1,intersection.length+2,intersection.length+3],`Trecho: ${region.join(', ')}. Presentes no Eclipse: ${intersection.join(', ')||'nenhum'}.`,5);
 const map=C.magnets[n];const count=map.filter(x=>C.familyOf(x)===0).length;add('magneto',`Desafio combinado: dos destinos Magneto da origem ${n}, quantos pertencem ao Cavalo 1?`,count,[count+1,count+2,count+3],`Destinos: ${map.join(', ')}. Cavalo 1 reúne os terminais 1, 4 e 7; classifique cada destino pelo último dígito.`,6);
 }
 return [...new Map(out.map(q=>[q.key,q])).values()];
}
const BANK=bank();
function generate(info){
 const used=new Set(),questions=[];const modules=shuffled(C.modules.map(m=>m.id));
 for(let i=0;i<info.count;i++){const module=modules[i%modules.length],target=info.level;let pool=BANK.filter(q=>q.module===module&&!used.has(q.key)&&q.level<=target&&q.level>=Math.max(1,target-2));if(!pool.length)pool=BANK.filter(q=>q.module===module&&!used.has(q.key));const q=shuffled(pool)[0];if(!q)throw Error('Banco insuficiente');used.add(q.key);questions.push({...q,id:crypto.randomUUID()});}
 return questions;
}
async function ensure(){if(!ready)ready=db.query(`CREATE TABLE IF NOT EXISTS student_exam_attempts (id CHAR(36) NOT NULL PRIMARY KEY,usuario_id CHAR(24) NOT NULL,dia DATE NOT NULL,tipo VARCHAR(20) NOT NULL,payload MEDIUMTEXT NOT NULL,respostas TEXT NOT NULL,revisao INT UNSIGNED NOT NULL DEFAULT 0,nota DECIMAL(5,2) NULL,fingerprint CHAR(64) NOT NULL,completed_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_student_exam_day(usuario_id,dia),UNIQUE KEY uq_student_exam_fingerprint(fingerprint)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`).catch(e=>{ready=null;throw e});return ready;}
function format(r){const payload=JSON.parse(r.payload),done=!!r.completed_at;return {id:r.id,date:typeof r.dia==='string'?r.dia.slice(0,10):new Date(r.dia).toISOString().slice(0,10),kind:r.tipo,title:labels[r.tipo],level:payload.level,difficulty:levels[payload.level],revision:Number(r.revisao),answers:JSON.parse(r.respostas),completed:done,score:done?Number(r.nota):null,questions:payload.questions.map(q=>{const {correct,explanation,key,...publicQ}=q;return done?{...publicQ,correct,explanation}:publicQ})};}
async function list(user){await ensure();return (await db.query('SELECT * FROM student_exam_attempts WHERE usuario_id=? ORDER BY dia DESC LIMIT 180',[user])).map(format);}
async function start(user,kind,now=new Date()){await ensure();const info=calendar(now);if(kind!==info.kind)throw error('Esta prova não está aberta hoje. Confira o calendário de Brasília.',403);const questions=generate(info),id=crypto.randomUUID(),fingerprint=crypto.createHash('sha256').update(questions.map(q=>q.key+':'+q.options.join('|')).join(';')).digest('hex');await db.query('INSERT IGNORE INTO student_exam_attempts (id,usuario_id,dia,tipo,payload,respostas,fingerprint) VALUES (?,?,?,?,?,?,?)',[id,user,info.date,kind,JSON.stringify({level:info.level,questions}),'{}',fingerprint]);const [r]=await db.query('SELECT * FROM student_exam_attempts WHERE usuario_id=? AND dia=?',[user,info.date]);if(!r)throw error('Não foi possível iniciar. Tente novamente.',503);return format(r);}
async function save(user,id,b,finish=false,now=new Date()){await ensure();return withTransaction(async tx=>{const [r]=await tx.query('SELECT * FROM student_exam_attempts WHERE id=? AND usuario_id=? FOR UPDATE',[id,user]);if(!r)throw error('Prova não encontrada.',404);const current=format(r);if(current.completed)return current;if(current.date!==calendar(now).date)throw error('O prazo desta prova terminou à meia-noite de Brasília.',403);if(current.revision!==b.revision)throw error('A prova mudou em outro dispositivo. Reabra para continuar.',409);const {questions}=JSON.parse(r.payload),answers=b.answers;if(!answers||typeof answers!=='object'||Array.isArray(answers)||Object.keys(answers).some(k=>!questions.some(q=>q.id===k)))throw error('Respostas inválidas.');for(const value of Object.values(answers))if(!Number.isInteger(value)||value<0||value>3)throw error('Alternativa inválida.');if(finish&&questions.some(q=>!Object.hasOwn(answers,q.id)))throw error('Responda todas as questões antes de entregar.');const score=finish?Math.round(questions.filter(q=>answers[q.id]===q.correct).length/questions.length*10000)/100:null;await tx.query('UPDATE student_exam_attempts SET respostas=?,revisao=revisao+1,nota=?,completed_at=? WHERE id=? AND usuario_id=?',[JSON.stringify(answers),score,finish?now:null,id,user]);return format({...r,respostas:JSON.stringify(answers),revisao:current.revision+1,nota:score,completed_at:finish?now:null});});}
module.exports={calendar,generate,bank:()=>BANK,labels,levels,list,start,save,format};
